---
  - name: conditionals
    hosts: localhost
    vars:
      db_package: mariadb-server
      db_service: mariadb
      db_users:
        - db_admin
        - db_user
      configure_database_path: /etc/my.cnf
    tasks:
    - name: Creates the Mariadb users
      user:
        name: "{{ item }}"
      with_items: "{{ db_users }}"
      when: inventory_hostname in groups['databases']
    - name: Installs DB Server
      yum:
        name: "{{ db_packages }}"
      when: db_packages is defined
    - name: configure DB Software
      include: configure_database.yml
      vars:
        extra_packages:
          - mariadb-bench
          - mariadb-libs
          - mariadb-test
      when: configure_database_path is defined

