---
  - name: Using Tags
    hosts: mailservers
    tasks:
    - name: include configure_mail.yml
      include: configure_mail.yml
      when: inventory_hostname in groups['mailservers']

    handlers:
    - name: start_postfix
      service:
        name: postfix
        state: started
    - name: start_dovecot
      service: 
        name: start_dovecot
        state: started
    - name: restart_postfix
      service:
        name: postfix
        state: restarted
        
